// GENERATED by tools/parse/build-portions.mjs — do not edit by hand.
//
// Curated portion weights lifted from the SFT generator's pools
// (tools/finetune/generate-synthetic.mjs), which are hand-checked against
// foods.db. These are the same numbers the estimator was TRAINED on; reading
// them directly beats hoping a 0.8B network reproduced them. The v9 gate showed
// that channel is lossy — the model returned 111 g per McNugget (a whole
// serving) and 143 g for a whole lasagna pan, against training values of 16 g
// and ~1400 g.
//
// Regenerate after changing pool weights:  node tools/parse/build-portions.mjs

/** Grams of ONE piece of a countable food. */
export const PIECE_GRAMS: Record<string, { unit: string; grams: number }> = {
  "roasted chicken breast": {
    "unit": "small roasted chicken breast",
    "grams": 140
  },
  "roasted chicken thighs": {
    "unit": "roasted chicken thigh",
    "grams": 75
  },
  "grilled beef patty": {
    "unit": "patty",
    "grams": 90
  },
  "grilled sirloin steak": {
    "unit": "small sirloin steak",
    "grams": 170
  },
  "cooked salmon": {
    "unit": "fillet",
    "grams": 150
  },
  "baked tilapia": {
    "unit": "fillet",
    "grams": 115
  },
  "cooked shrimp": {
    "unit": "piece",
    "grams": 12
  },
  "scrambled eggs": {
    "unit": "scrambled egg",
    "grams": 61
  },
  "hard-boiled eggs": {
    "unit": "hard-boiled egg",
    "grams": 50
  },
  "fried eggs": {
    "unit": "fried egg",
    "grams": 46
  },
  "canned tuna": {
    "unit": "can",
    "grams": 140
  },
  "grilled pork chop": {
    "unit": "grilled pork chop",
    "grams": 150
  },
  "bacon": {
    "unit": "slice",
    "grams": 9
  },
  "breakfast sausage": {
    "unit": "link",
    "grams": 27
  },
  "sliced deli ham": {
    "unit": "slice",
    "grams": 28
  },
  "hot dogs": {
    "unit": "hot dog",
    "grams": 102
  },
  "burgers": {
    "unit": "burger",
    "grams": 200
  },
  "chicken nuggets": {
    "unit": "nugget",
    "grams": 16
  },
  "fried chicken wings": {
    "unit": "wing",
    "grams": 30
  },
  "whole wheat toast": {
    "unit": "slice",
    "grams": 26
  },
  "white bread": {
    "unit": "slice",
    "grams": 27
  },
  "plain bagel": {
    "unit": "plain bagel",
    "grams": 99
  },
  "butter croissant": {
    "unit": "butter croissant",
    "grams": 57
  },
  "blueberry muffin": {
    "unit": "blueberry muffin",
    "grams": 113
  },
  "pancakes": {
    "unit": "pancake",
    "grams": 41
  },
  "mini pancakes": {
    "unit": "mini pancake",
    "grams": 20
  },
  "french toast": {
    "unit": "slice",
    "grams": 65
  },
  "baked potato": {
    "unit": "medium baked potato",
    "grams": 173
  },
  "baked sweet potato": {
    "unit": "medium sweet potato",
    "grams": 114
  },
  "flour tortilla": {
    "unit": "large tortilla",
    "grams": 70
  },
  "doughnut": {
    "unit": "doughnut",
    "grams": 60
  },
  "tomato": {
    "unit": "medium tomato",
    "grams": 123
  },
  "red bell pepper": {
    "unit": "medium red bell pepper",
    "grams": 119
  },
  "butter": {
    "unit": "pat",
    "grams": 5
  },
  "avocado": {
    "unit": "half avocado",
    "grams": 100
  },
  "almonds": {
    "unit": "handful",
    "grams": 28
  },
  "walnuts": {
    "unit": "handful",
    "grams": 28
  },
  "banana": {
    "unit": "medium banana",
    "grams": 118
  },
  "apple": {
    "unit": "medium apple",
    "grams": 182
  },
  "orange": {
    "unit": "medium orange",
    "grams": 131
  },
  "peach": {
    "unit": "medium peach",
    "grams": 150
  },
  "cheddar cheese": {
    "unit": "slice",
    "grams": 21
  },
  "swiss cheese": {
    "unit": "slice",
    "grams": 28
  },
  "potato chips": {
    "unit": "small bag",
    "grams": 28
  },
  "chocolate chip cookies": {
    "unit": "chocolate chip cookie",
    "grams": 15
  },
  "granola bar": {
    "unit": "granola bar",
    "grams": 25
  },
  "protein bar": {
    "unit": "protein bar",
    "grams": 60
  },
  "rice cake": {
    "unit": "rice cake",
    "grams": 9
  },
  "mozzarella sticks": {
    "unit": "mozzarella stick",
    "grams": 20
  },
  "meatballs": {
    "unit": "meatball",
    "grams": 30
  },
  "chicken tenders": {
    "unit": "chicken tender",
    "grams": 45
  },
  "mini muffins": {
    "unit": "mini muffin",
    "grams": 30
  },
  "potstickers": {
    "unit": "potsticker",
    "grams": 24
  },
  "dumplings": {
    "unit": "dumpling",
    "grams": 24
  },
  "oreos": {
    "unit": "oreo",
    "grams": 11
  },
  "tater tots": {
    "unit": "tater tot",
    "grams": 15
  },
  "shrimp tempura": {
    "unit": "piece",
    "grams": 20
  },
  "regular beer": {
    "unit": "can",
    "grams": 356
  },
  "bubble tea": {
    "unit": "medium cup",
    "grams": 500
  },
  "fruit smoothie": {
    "unit": "medium cup",
    "grams": 400
  },
  "french fries": {
    "unit": "medium serving",
    "grams": 115
  },
  "beef tacos": {
    "unit": "beef taco",
    "grams": 100
  },
  "cheese pizza": {
    "unit": "slice",
    "grams": 107
  },
  "pepperoni pizza": {
    "unit": "slice",
    "grams": 111
  },
  "chili": {
    "unit": "bowl",
    "grams": 300
  },
  "lasagna": {
    "unit": "piece",
    "grams": 255
  },
  "pad thai": {
    "unit": "serving",
    "grams": 350
  },
  "chicken fried rice": {
    "unit": "serving",
    "grams": 350
  },
  "beef stew": {
    "unit": "bowl",
    "grams": 300
  },
  "chicken pot pie": {
    "unit": "serving",
    "grams": 250
  },
  "burrito bowl": {
    "unit": "serving",
    "grams": 450
  }
};

/** Grams of a WHOLE dish, for "half a pizza" / "a quarter of the lasagna". */
export const DISH_GRAMS: Record<string, { grams: number }> = {
  "lasagna": {
    "grams": 1400
  },
  "chocolate cake": {
    "grams": 950
  },
  "cake": {
    "grams": 950
  },
  "apple pie": {
    "grams": 1025
  },
  "pumpkin pie": {
    "grams": 1025
  },
  "tuna casserole": {
    "grams": 1450
  },
  "pizza": {
    "grams": 925
  },
  "rotisserie chicken": {
    "grams": 900
  },
  "burrito": {
    "grams": 430
  }
};
