// Validates tools/db-data/food-aliases.json against the shipped foods.db and
// emits the app-side copy (mobile/src/lib/food-aliases.ts).
//
// An alias is only useful if its target phrase still resolves to the row it was
// written for, and DB rebuilds move rows around. So every alias is resolved
// here with the SAME ranking the resolver uses, and every entry in `expect` is
// checked against the row it names. A stale alias fails the build instead of
// silently sending "a coke" somewhere else.
//
//   node tools/db/build-aliases.mjs
//
// Single source of truth is the JSON; the .ts is a generated artifact.

import { DatabaseSync } from 'node:sqlite';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..', '..');
const data = JSON.parse(readFileSync(join(ROOT, 'tools/db-data/food-aliases.json'), 'utf8'));
const db = new DatabaseSync(join(ROOT, 'mobile/assets/foods.db'), { readOnly: true });

const STOP = new Set(['a', 'an', 'the', 'of', 'with', 'and', 'in', 'on', 'or', 'for', 'to']);

// Mirrors the resolver's 'all'-scope ranking, including the alcohol de-ranking
// (see mobile/src/lib/foods.ts) so validation matches runtime behaviour.
const ALCOHOL_CATEGORIES = ['Liquor and cocktails', 'Beer', 'Wine'];
const ALCOHOL_WORD_RE = /\b(?:beer|wine|liquor|vodka|rum|whiskey|whisky|gin|tequila|bourbon|cocktail|spiked|hard)\b/i;

function resolve(query) {
  const all = query.toLowerCase().replace(/[^a-z0-9]+/g, ' ').split(' ').filter(Boolean);
  const meaningful = all.filter((t) => !STOP.has(t));
  const tokens = meaningful.length ? meaningful : all;
  if (!tokens.length) return null;
  const where = tokens.map(() => "(' ' || name_norm) LIKE ? ESCAPE '\\'").join(' AND ');
  const params = tokens.map((t) => `% ${t.replace(/[\\%_]/g, (c) => `\\${c}`)}%`);
  const penalty = ALCOHOL_WORD_RE.test(query)
    // A constant integer in ORDER BY is read as a COLUMN ORDINAL by SQLite —
    // and parentheses do not change that — so the no-op sort key must be NULL.
    ? 'NULL'
    : `CASE WHEN category IN (${ALCOHOL_CATEGORIES.map(() => '?').join(',')}) THEN 1 ELSE 0 END`;
  const penaltyParams = ALCOHOL_WORD_RE.test(query) ? [] : ALCOHOL_CATEGORIES;
  return db.prepare(
    `SELECT name, category FROM foods WHERE ${where}
     ORDER BY CASE WHEN (' ' || name_norm || ' ') LIKE ? ESCAPE '\\' THEN 0 ELSE 1 END,
              CASE WHEN name_norm LIKE ? ESCAPE '\\' THEN 0 ELSE 1 END,
              ${penalty}, LENGTH(name_norm) LIMIT 1`
  ).get(...params, ...penaltyParams, `% ${tokens[0]} %`, `${tokens[0]}%`);
}

let failures = 0;
console.log('resolving each alias target:');
for (const [alias, phrase] of Object.entries(data.aliases)) {
  const row = resolve(phrase);
  if (!row) { console.error(`  FAIL ${alias}: target phrase resolves to nothing`); failures++; continue; }
  console.log(`  ${alias.padEnd(12)} -> ${row.name}`);
}

console.log('\nchecking expectations:');
for (const [alias, wantName] of Object.entries(data.expect ?? {})) {
  const phrase = data.aliases[alias];
  if (!phrase) { console.error(`  FAIL ${alias}: named in expect but not in aliases`); failures++; continue; }
  const row = resolve(phrase);
  if (row?.name !== wantName) {
    console.error(`  FAIL ${alias}: resolves to ${JSON.stringify(row?.name ?? null)}, expected ${JSON.stringify(wantName)}`);
    failures++;
  } else {
    console.log(`  ok   ${alias.padEnd(12)} -> ${wantName}`);
  }
}

if (failures) {
  console.error(`\n${failures} alias failure(s) — not writing the app copy`);
  process.exit(1);
}

const ts = `// GENERATED by tools/db/build-aliases.mjs — do not edit by hand.
//
// Everyday words people type that foods.db has no token for, mapped to a search
// phrase that resolves to the right canonical row. "coke" appears in 0 of the
// 14,558 rows; "cola" and "soda" DO appear but rank onto cocktail rows
// ("Rum and cola", "Vodka and soda") because those names are shorter and the
// resolver's last tiebreak is name length — so the macros came back alcoholic.
//
// Longest alias wins, so "diet coke" beats "coke". Targets are validated
// against the shipped DB at build time.
//
// Regenerate:  node tools/db/build-aliases.mjs

export const FOOD_ALIASES: Record<string, string> = ${JSON.stringify(data.aliases, null, 2)};

/** Aliases longest-first, so a more specific phrase matches before a shorter one. */
const ALIASES_BY_LENGTH = Object.keys(FOOD_ALIASES).sort((a, b) => b.length - a.length);

/**
 * The canonical search phrase for a query that names an aliased food, or null.
 * Matches on whole words so "coke" hits but "cokes-something" does not, and
 * requires the alias to be essentially the whole query — "rum and coke" is a
 * cocktail and must NOT be rewritten to plain cola.
 */
export function aliasFor(query: string): string | null {
  const q = String(query ?? '').toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim();
  if (!q) return null;
  for (const alias of ALIASES_BY_LENGTH) {
    if (q === alias) return FOOD_ALIASES[alias];
    // Allow a leading article or a trailing size word ("a coke", "coke 12 oz").
    const m = new RegExp(\`^(?:a |an |the )?\${alias}(?: [0-9].*)?$\`).exec(q);
    if (m) return FOOD_ALIASES[alias];
  }
  return null;
}
`;
writeFileSync(join(ROOT, 'mobile/src/lib/food-aliases.ts'), ts);
console.log('\nwrote mobile/src/lib/food-aliases.ts');
