// GENERATED by tools/db/build-aliases.mjs — do not edit by hand.
//
// Everyday words people type that foods.db has no token for, mapped to a search
// phrase that resolves to the right canonical row. "coke" appears in 0 of the
// 14,558 rows; "cola" and "soda" DO appear but rank onto cocktail rows
// ("Rum and cola", "Vodka and soda") because those names are shorter and the
// resolver's last tiebreak is name length — so the macros came back alcoholic.
//
// Longest alias wins, so "diet coke" beats "coke". Targets are validated
// against the shipped DB at build time.
//
// Regenerate:  node tools/db/build-aliases.mjs

export const FOOD_ALIASES: Record<string, string> = {
  "coke": "beverages carbonated cola regular",
  "coca cola": "beverages carbonated cola regular",
  "cola": "beverages carbonated cola regular",
  "pepsi": "beverages carbonated cola regular",
  "soda": "beverages carbonated cola regular",
  "pop": "beverages carbonated cola regular",
  "soft drink": "beverages carbonated cola regular",
  "diet coke": "beverages carbonated low calorie cola or pepper types with sodium saccharin contains caffeine",
  "diet cola": "beverages carbonated low calorie cola or pepper types with sodium saccharin contains caffeine",
  "diet soda": "beverages carbonated low calorie cola or pepper types with sodium saccharin contains caffeine",
  "diet pepsi": "beverages carbonated low calorie cola or pepper types with sodium saccharin contains caffeine"
};

/** Aliases longest-first, so a more specific phrase matches before a shorter one. */
const ALIASES_BY_LENGTH = Object.keys(FOOD_ALIASES).sort((a, b) => b.length - a.length);

/**
 * The canonical search phrase for a query that names an aliased food, or null.
 * Matches on whole words so "coke" hits but "cokes-something" does not, and
 * requires the alias to be essentially the whole query — "rum and coke" is a
 * cocktail and must NOT be rewritten to plain cola.
 */
export function aliasFor(query: string): string | null {
  const q = String(query ?? '').toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim();
  if (!q) return null;
  for (const alias of ALIASES_BY_LENGTH) {
    if (q === alias) return FOOD_ALIASES[alias];
    // Allow a leading article or a trailing size word ("a coke", "coke 12 oz").
    const m = new RegExp(`^(?:a |an |the )?${alias}(?: [0-9].*)?$`).exec(q);
    if (m) return FOOD_ALIASES[alias];
  }
  return null;
}
